openapi: 3.0.0
info:
  title: Main API
  version: 1.0.0
paths:
  /api/ping:
    $ref: './ping.yaml#/paths/~1api~1ping'
  /api/echo:
    $ref: './echo.yaml#/paths/~1api~1echo'
  /files/{fileId}/download:
    $ref: './files.yaml#/paths/~1files~1{fileId}~1download'
components:
  schemas:
    PingResponse:
      $ref: './ping.yaml#/components/schemas/PingResponse'
    EchoResponse:
      $ref: './echo.yaml#/components/schemas/EchoResponse'
